### ISSUE TITLE
Failed to start listener

### ISSUE THREAD

**Issue by mangojuice123** [kevwan/tproxy#8]
Hi,
I just ran this command `tproxy -p 3307 -r localhost:3306` and always get this output:
`[x] Failed to start listener: failed to start listener: listen tcp: lookup localhost: no such host`
I changed `localhost` to `127.0.0.1` but it still failed.

**Comment by kevwan** [comment]
You might need to add `127.0.0.1	localhost` to your hosts file.

**Comment by mangojuice123** [comment]
> You might need to add `127.0.0.1 localhost` to your hosts file.

It works like a charm.
